In [241]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

# Charger le fichier CSV
data = pd.read_csv("pp.csv")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%H:%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Enregistrer les données au format CSV
data.to_csv("pp_updated.csv", index=False)

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"])

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = LogisticRegression()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict_proba(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


KeyError: 'timestamp'

In [237]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression

# Load the CSV file
data = pd.read_csv("pp.csv")

# Convert the timestamp column to datetime type
data["timestamp"] = pd.to_datetime(data["timestamp"])

# Create a new column "time_elapsed" in seconds
data["time_elapsed"] = data["timestamp"].dt.hour * 3600 + data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second

# Label encode the categorical variables
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Separate the predictor variables from the target variable
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Model accuracy:", accuracy)
print("Confusion matrix:\n", confusion_mat)


KeyError: 'timestamp'

In [16]:
data = pd.read_csv("pp.csv", delimiter="\t")

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Id_Website  799 non-null    int64 
 1   Id_proxy    799 non-null    int64 
 2   Success     799 non-null    bool  
 3   timestamp   799 non-null    object
dtypes: bool(1), int64(2), object(1)
memory usage: 19.6+ KB


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.hour * 3600 + data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.7625
Matrice de confusion :
 [[108   8]
 [ 30  14]]


In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.7625
Matrice de confusion :
 [[106  10]
 [ 28  16]]


In [20]:
data["time_elapsed"]

0       57
1       26
2      105
3       76
4       50
      ... 
794     17
795    254
796     24
797    194
798    131
Name: time_elapsed, Length: 799, dtype: int32

In [35]:
new_data = pd.read_csv("new_data.csv", delimiter="\t")
new_data

Id_Website  Id_proxy  Success timestamp
0           388        24    False   0:32:13
1            72        11    False   0:01:40
2           424        31     True   0:21:18
3           714        35    False   0:38:13
4           395        35    False   0:04:37
..          ...       ...      ...       ...
196         724        58    False   0:02:93
197         452         2    False   0:22:18
198           5         5    False   0:50:08
199         160        23    False   3:10:75
200         448         5    False   3:08:51

[201 rows x 4 columns]

In [36]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Id_Website  201 non-null    int64 
 1   Id_proxy    201 non-null    int64 
 2   Success     201 non-null    bool  
 3   timestamp   201 non-null    object
dtypes: bool(1), int64(2), object(1)
memory usage: 5.0+ KB


In [37]:
#new_data = pd.read_csv("new_data.csv", delimiter="\t")

# Prétraiter les nouvelles données
# Assurez-vous d'appliquer les mêmes transformations que pour les données d'entraînement
new_data["timestamp"] = pd.to_datetime(new_data["timestamp"], format="%M:%S:%f")
new_data["tierces"] = new_data["timestamp"].dt.microsecond // 10000

new_data["time_elapsed"] = new_data["timestamp"].dt.minute * 60 + new_data["timestamp"].dt.second
# Sélectionner les mêmes variables prédictives que pour l'entraînement
X_new = new_data[["Id_Website", "Id_proxy", "time_elapsed"]]

# Faire les prédictions sur les nouvelles données
predictions = model.predict(X_new)

# Afficher les prédictions
print(predictions)

[0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [38]:
new_data["Success"] = label_encoder.fit_transform(new_data["Success"])

target = new_data["Success"]


In [44]:
predictions - target.tolist()

array([ 0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0, -1,  1,  1,  0,  0,  0,
        0,  0, -1, -1,  0,  1, -1,  0,  1,  0,  0,  0, -1,  0, -1, -1,  0,
       -1,  0,  0,  0, -1,  0,  1,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,
       -1,  0,  0, -1,  0, -1,  1,  0,  1,  1, -1,  0,  0,  0, -1,  0,  0,
        1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,
        0,  0, -1,  0, -1,  0,  1,  1,  0,  0, -1,  0,  0,  0,  1, -1,  0,
       -1, -1,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,  1,  0,
        1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  1,
        0,  0,  0,  0, -1,  1,  1, -1,  1, -1,  0, -1, -1,  0,  0,  0,  0,
        0,  0, -1,  1,  1, -1,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
      dtype=int64)

In [43]:
accuracy = accuracy_score(target, predictions)
confusion_mat = confusion_matrix(target, predictions)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.6766169154228856
Matrice de confusion :
 [[134  21]
 [ 44   2]]


In [196]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = GradientBoostingClassifier()
pipeline_model6 = make_pmml_pipeline(model)
pipeline_model6.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model6.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.74375
Matrice de confusion :
 [[110   6]
 [ 35   9]]


In [197]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model6, "trained_model6.pmml")

In [194]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
# from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = SVC()
pipeline_model5 = make_pmml_pipeline(model)
pipeline_model5.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model5.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[116   0]
 [ 44   0]]


In [195]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model5, "trained_model5.pmml")

In [191]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = DecisionTreeClassifier()
pipeline_model4 = make_pmml_pipeline(model)
pipeline_model4.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model4.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.7125
Matrice de confusion :
 [[94 22]
 [24 20]]


In [192]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model4, "trained_model4.pmml")

In [137]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = KNeighborsClassifier()
pipeline_model3 = make_pmml_pipeline(model)
pipeline_model3.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model3.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[104  12]
 [ 32  12]]


In [138]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model3, "trained_model3.pmml")

In [133]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = MLPClassifier()
pipeline_model2 = make_pmml_pipeline(model)
pipeline_model2.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model2.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.74375
Matrice de confusion :
 [[115   1]
 [ 40   4]]


In [134]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model2, "trained_model2.pmml")

In [224]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = SGDClassifier()
pipeline_model7 = make_pmml_pipeline(model)
pipeline_model7.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model7.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[116   0]
 [ 44   0]]


In [225]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model7, "trained_model7.pmml")

In [278]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = LogisticRegression()
pipeline_model8 = make_pmml_pipeline(model)
pipeline_model8.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred_proba = pipeline_model8.predict_proba(X_test)
y_pred = np.argmax(y_pred_proba, axis=1)
# print(y_pred_proba)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[116   0]
 [ 44   0]]


In [279]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model8, "trained_model8.pmml")

In [242]:
# Convert y_pred_proba to DataFrame
y_pred_proba_df = pd.DataFrame(y_pred_proba, columns=['Prob_0', 'Prob_1'])

# Reset index of X_test for proper concatenation
X_test_reset = X_test.reset_index(drop=True)

# Concatenate along the column axis
result = pd.concat([X_test_reset, y_pred_proba_df], axis=1)

print(result)


     Id_Website  Id_proxy  time_elapsed    Prob_0    Prob_1
0             7        21            81  0.745024  0.254976
1            38        38           206  0.716569  0.283431
2           684        42            47  0.772487  0.227513
3           231        12           124  0.723996  0.276004
4           190        50            79  0.767657  0.232343
..          ...       ...           ...       ...       ...
155         351        39            93  0.755498  0.244502
156         261        46           194  0.727650  0.272350
157         578        44           124  0.749816  0.250184
158         267        13            78  0.740302  0.259698
159          66        10            80  0.736903  0.263097

[160 rows x 5 columns]


In [244]:
result.to_csv("result.csv")

In [ ]:
# df for pp.csv
import pandas as pd

data = pd.read_csv("pp.csv", delimiter="\t")

data['original_timestamp'] = data['timestamp']

data['timestamp'] = pd.to_datetime(data['timestamp'], format='%M:%S:%f')

data = data.sort_values(['Id_Website', 'Id_proxy', 'timestamp'])

grouped = data.groupby(['Id_Website', 'Id_proxy'])

new_data = pd.DataFrame(columns=['Id_Website', 'Id_proxy', 'timestamp1', 'success1', 'timestamp2', 'success2'])


for name, group in grouped:
    if len(group) < 2:
        continue

    for i in range(len(group) - 1):
        new_row = {'Id_Website': name[0], 
                   'Id_proxy': name[1], 
                   'timestamp1': group.iloc[i]['original_timestamp'], 
                   'success1': group.iloc[i]['Success'], 
                   'timestamp2': group.iloc[i + 1]['original_timestamp'], 
                   'success2': group.iloc[i + 1]['Success']}
        new_data = new_data.append(new_row, ignore_index=True)

print(new_data)

In [ ]:
new_data.to_csv("df.csv")

In [ ]:
# data for ppp.csv ppp.csv is total willRespond
import pandas as pd

data = pd.read_csv("ppp.csv", delimiter=",")

data['original_timestamp'] = data['timestamp']

data['timestamp'] = pd.to_datetime(data['timestamp'], format='%M:%S:%f')

data = data.sort_values(['Id_Website', 'Id_Proxy', 'timestamp'])

grouped = data.groupby(['Id_Website', 'Id_Proxy'])

new_data = pd.DataFrame(columns=['Id_Website', 'Id_Proxy', 'timestamp1', 'success1', 'timestamp2', 'success2'])

for name, group in grouped:
    if len(group) < 2:
        continue

    for i in range(len(group) - 1):
        new_row = {'Id_Website': name[0], 
                   'Id_Proxy': name[1], 
                   'timestamp1': group.iloc[i]['original_timestamp'], 
                   'success(-1)': group.iloc[i]['success'], 
                   'timestamp2': group.iloc[i + 1]['original_timestamp'], 
                   'success2': group.iloc[i + 1]['success']}
        new_data = new_data.append(new_row, ignore_index=True)

print(new_data)

In [ ]:
data = pd.read_csv("data.csv", delimiter=",")

In [ ]:
new_data.to_csv("data.csv")

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
new_data = pd.read_csv("data.csv", delimiter=",")
# Convertir la colonne timestamp en type datetime
new_data["timestamp1"] = pd.to_datetime(new_data["timestamp1"], format="%M:%S:%f")
new_data["tierces1"] = new_data["timestamp1"].dt.microsecond // 10000
new_data["timestamp2"] = pd.to_datetime(new_data["timestamp2"], format="%M:%S:%f")
new_data["tierces2"] = new_data["timestamp2"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
new_data["success(-1)"] = label_encoder.fit_transform(new_data["success1"])
new_data["success"] = label_encoder.fit_transform(new_data["success2"])

# Créer une nouvelle colonne "time_elapsed" en secondes
new_data["time_elapsed1"] = new_data["timestamp1"].dt.minute * 60 + new_data["timestamp1"].dt.second + new_data["tierces1"]
new_data["time_elapsed2"] = new_data["timestamp2"].dt.minute * 60 + new_data["timestamp2"].dt.second + new_data["tierces2"]

# Séparer les variables prédictives de la variable cible
X = new_data[["Id_Website", "Id_Proxy", "time_elapsed1", "time_elapsed2", "success1"]]
y = new_data["success2"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = LogisticRegression()
pipeline_model8 = make_pmml_pipeline(model)
pipeline_model8.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred_proba = pipeline_model8.predict_proba(X_test)
y_pred = np.argmax(y_pred_proba, axis=1)
print(y_pred_proba)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

In [25]:
import pandas as pd
import numpy as np
data = pd.read_csv("data.csv", delimiter=",")


# 计算时间差并将结果保存到新列 "time_difference"
data['time_difference'] = pd.to_datetime(data['timestamp2'], format='%M:%S:%f') - pd.to_datetime(data['timestamp1'], format='%M:%S:%f')
def format_timedelta(td):
    hours, remainder = divmod(td.total_seconds(), 60)
    minutes, seconds = divmod(remainder, 60)
    milliseconds = td.microseconds // 10000
    return f"{int(minutes):02d}:{int(seconds):02d}:{int(milliseconds):02d}"

data['time_difference'] = data['time_difference'].apply(format_timedelta)



# 打印结果
print(data)

        Unnamed: 0  Id_Website  Id_Proxy timestamp1  success1 timestamp2  \
0                0           1         6    0:00:72     False    0:00:89   
1                1           1         6    0:00:89     False    0:00:98   
2                2           1         6    0:00:98     False    0:01:06   
3                3           1         6    0:01:06     False    0:01:17   
4                4           1         6    0:01:17     False    0:01:18   
...            ...         ...       ...        ...       ...        ...   
698156      698156         800        60    3:10:87     False    3:10:90   
698157      698157         800        60    3:10:90      True    3:11:56   
698158      698158         800        60    3:11:56     False    3:11:92   
698159      698159         800        60    3:11:92     False    3:12:03   
698160      698160         800        60    3:12:03     False    3:12:49   

        success2 time_difference  
0          False        00:00:17  
1          False 

In [26]:
data.to_csv("data2.csv")

In [46]:
df = pd.read_csv("data2.csv", delimiter=",")
df = df.drop(df.columns[df.columns.str.contains('Unnamed')], axis= 1)

df

Id_Website  Id_Proxy timestamp1  success1 timestamp2  success2  \
0                1         6    0:00:72     False    0:00:89     False   
1                1         6    0:00:89     False    0:00:98     False   
2                1         6    0:00:98     False    0:01:06     False   
3                1         6    0:01:06     False    0:01:17     False   
4                1         6    0:01:17     False    0:01:18     False   
...            ...       ...        ...       ...        ...       ...   
680587         784        13    0:01:63     False    0:01:98     False   
680588         784        13    0:01:98     False    0:02:11     False   
680589         784        13    0:02:11     False    0:02:43     False   
680590         784        13    0:02:43     False    0:02:69     False   
680591         784        13    0:02:69     False    0:02:78     False   

       time_difference  
0             00:00:17  
1             00:00:09  
2             00:00:08  
3             00:00:11  
4             00:00:01  
...                ...  
680587        00:00:35  
680588        00:00:13  
680589        00:00:32  
680590        00:00:26  
680591        00:00:09  

[680592 rows x 7 columns]

In [47]:
df = df.rename(columns={'success1': 'success(-1)', 'success2': 'success'})

df

Id_Website  Id_Proxy timestamp1  success(-1) timestamp2  success  \
0                1         6    0:00:72        False    0:00:89    False   
1                1         6    0:00:89        False    0:00:98    False   
2                1         6    0:00:98        False    0:01:06    False   
3                1         6    0:01:06        False    0:01:17    False   
4                1         6    0:01:17        False    0:01:18    False   
...            ...       ...        ...          ...        ...      ...   
680587         784        13    0:01:63        False    0:01:98    False   
680588         784        13    0:01:98        False    0:02:11    False   
680589         784        13    0:02:11        False    0:02:43    False   
680590         784        13    0:02:43        False    0:02:69    False   
680591         784        13    0:02:69        False    0:02:78    False   

       time_difference  
0             00:00:17  
1             00:00:09  
2             00:00:08  
3             00:00:11  
4             00:00:01  
...                ...  
680587        00:00:35  
680588        00:00:13  
680589        00:00:32  
680590        00:00:26  
680591        00:00:09  

[680592 rows x 7 columns]

In [48]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

df["time_difference"] = pd.to_datetime(df["time_difference"], format="%M:%S:%f")
df["tierces"] = df["time_difference"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
df["success(-1)"] = label_encoder.fit_transform(df["success(-1)"])
df["success"] = label_encoder.fit_transform(df["success"])

# # Créer une nouvelle colonne "time_elapsed" en secondes
df["time_difference_elapsed"] = df["time_difference"].dt.minute * 60 + df["time_difference"].dt.second + df["tierces"]

# Séparer les variables prédictives de la variable cible
X = df[["Id_Website", "Id_Proxy", "success(-1)", "time_difference_elapsed"]]
y = df["success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = LogisticRegression()
pipeline_model8 = make_pmml_pipeline(model)
pipeline_model8.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred_proba = pipeline_model8.predict_proba(X_test)
y_pred = np.argmax(y_pred_proba, axis=1)
print(y_pred_proba)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

[[0.88202225 0.11797775]
 [0.88157339 0.11842661]
 [0.88112427 0.11887573]
 ...
 [0.88314608 0.11685392]
 [0.88312652 0.11687348]
 [0.88211986 0.11788014]]
Précision du modèle : 0.8237791932059448
Matrice de confusion :
 [[90505 11929]
 [12058 21627]]


In [50]:
df_test = pd.read_csv("test_data.csv", delimiter=",")
df_test = df_test.drop(df_test.columns[df_test.columns.str.contains('Unnamed')], axis= 1)

df_test

Id_Website  Id_Proxy timestamp1  success1 timestamp2  success2  \
0             784        13    0:02:78     False    0:03:02     False   
1             784        13    0:03:02     False    0:03:05     False   
2             784        13    0:03:05     False    0:03:21     False   
3             784        13    0:03:21     False    0:03:28     False   
4             784        13    0:03:28     False    0:03:45     False   
...           ...       ...        ...       ...        ...       ...   
17564         800        60    3:10:87     False    3:10:90      True   
17565         800        60    3:10:90      True    3:11:56     False   
17566         800        60    3:11:56     False    3:11:92     False   
17567         800        60    3:11:92     False    3:12:03     False   
17568         800        60    3:12:03     False    3:12:49     False   

      time_difference  
0            00:00:24  
1            00:00:03  
2            00:00:16  
3            00:00:07  
4            00:00:17  
...               ...  
17564        00:00:03  
17565        00:00:66  
17566        00:00:36  
17567        00:00:11  
17568        00:00:46  

[17569 rows x 7 columns]

In [51]:
df_test = df_test.rename(columns={'success1': 'success(-1)', 'success2': 'success'})

df_test

Id_Website  Id_Proxy timestamp1  success(-1) timestamp2  success  \
0             784        13    0:02:78        False    0:03:02    False   
1             784        13    0:03:02        False    0:03:05    False   
2             784        13    0:03:05        False    0:03:21    False   
3             784        13    0:03:21        False    0:03:28    False   
4             784        13    0:03:28        False    0:03:45    False   
...           ...       ...        ...          ...        ...      ...   
17564         800        60    3:10:87        False    3:10:90     True   
17565         800        60    3:10:90         True    3:11:56    False   
17566         800        60    3:11:56        False    3:11:92    False   
17567         800        60    3:11:92        False    3:12:03    False   
17568         800        60    3:12:03        False    3:12:49    False   

      time_difference  
0            00:00:24  
1            00:00:03  
2            00:00:16  
3            00:00:07  
4            00:00:17  
...               ...  
17564        00:00:03  
17565        00:00:66  
17566        00:00:36  
17567        00:00:11  
17568        00:00:46  

[17569 rows x 7 columns]

In [52]:
y = df_test.success
y

0        False
1        False
2        False
3        False
4        False
         ...  
17564     True
17565    False
17566    False
17567    False
17568    False
Name: success, Length: 17569, dtype: bool

In [53]:
df_test.drop(columns=['success'])

Id_Website  Id_Proxy timestamp1  success(-1) timestamp2 time_difference
0             784        13    0:02:78        False    0:03:02        00:00:24
1             784        13    0:03:02        False    0:03:05        00:00:03
2             784        13    0:03:05        False    0:03:21        00:00:16
3             784        13    0:03:21        False    0:03:28        00:00:07
4             784        13    0:03:28        False    0:03:45        00:00:17
...           ...       ...        ...          ...        ...             ...
17564         800        60    3:10:87        False    3:10:90        00:00:03
17565         800        60    3:10:90         True    3:11:56        00:00:66
17566         800        60    3:11:56        False    3:11:92        00:00:36
17567         800        60    3:11:92        False    3:12:03        00:00:11
17568         800        60    3:12:03        False    3:12:49        00:00:46

[17569 rows x 6 columns]

In [54]:
df_test["time_difference"] = pd.to_datetime(df_test["time_difference"], format="%M:%S:%f")
df_test["tierces"] = df_test["time_difference"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
df_test["success(-1)"] = label_encoder.fit_transform(df_test["success(-1)"])
df_test["success"] = label_encoder.fit_transform(df_test["success"])

# # Créer une nouvelle colonne "time_elapsed" en secondes
df_test["time_difference_elapsed"] = df_test["time_difference"].dt.minute * 60 + df_test["time_difference"].dt.second + df_test["tierces"]

# Séparer les variables prédictives de la variable cible
X = df_test[["Id_Website", "Id_Proxy", "success(-1)", "time_difference_elapsed"]]

y_test = pipeline_model8.predict(X)



In [55]:
accuracy = accuracy_score(y, y_test)

accuracy

0.8355626387386874

In [56]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model8, "trained_model9.pmml")