In [241]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

# Charger le fichier CSV
data = pd.read_csv("pp.csv")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%H:%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Enregistrer les données au format CSV
data.to_csv("pp_updated.csv", index=False)

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"])

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = LogisticRegression()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict_proba(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


KeyError: 'timestamp'

In [237]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression

# Load the CSV file
data = pd.read_csv("pp.csv")

# Convert the timestamp column to datetime type
data["timestamp"] = pd.to_datetime(data["timestamp"])

# Create a new column "time_elapsed" in seconds
data["time_elapsed"] = data["timestamp"].dt.hour * 3600 + data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second

# Label encode the categorical variables
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Separate the predictor variables from the target variable
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Model accuracy:", accuracy)
print("Confusion matrix:\n", confusion_mat)


KeyError: 'timestamp'

In [16]:
data = pd.read_csv("pp.csv", delimiter="\t")

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Id_Website  799 non-null    int64 
 1   Id_proxy    799 non-null    int64 
 2   Success     799 non-null    bool  
 3   timestamp   799 non-null    object
dtypes: bool(1), int64(2), object(1)
memory usage: 19.6+ KB


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.hour * 3600 + data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.7625
Matrice de confusion :
 [[108   8]
 [ 30  14]]


In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.7625
Matrice de confusion :
 [[106  10]
 [ 28  16]]


In [20]:
data["time_elapsed"]

0       57
1       26
2      105
3       76
4       50
      ... 
794     17
795    254
796     24
797    194
798    131
Name: time_elapsed, Length: 799, dtype: int32

In [35]:
new_data = pd.read_csv("new_data.csv", delimiter="\t")
new_data

Id_Website  Id_proxy  Success timestamp
0           388        24    False   0:32:13
1            72        11    False   0:01:40
2           424        31     True   0:21:18
3           714        35    False   0:38:13
4           395        35    False   0:04:37
..          ...       ...      ...       ...
196         724        58    False   0:02:93
197         452         2    False   0:22:18
198           5         5    False   0:50:08
199         160        23    False   3:10:75
200         448         5    False   3:08:51

[201 rows x 4 columns]

In [36]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Id_Website  201 non-null    int64 
 1   Id_proxy    201 non-null    int64 
 2   Success     201 non-null    bool  
 3   timestamp   201 non-null    object
dtypes: bool(1), int64(2), object(1)
memory usage: 5.0+ KB


In [37]:
#new_data = pd.read_csv("new_data.csv", delimiter="\t")

# Prétraiter les nouvelles données
# Assurez-vous d'appliquer les mêmes transformations que pour les données d'entraînement
new_data["timestamp"] = pd.to_datetime(new_data["timestamp"], format="%M:%S:%f")
new_data["tierces"] = new_data["timestamp"].dt.microsecond // 10000

new_data["time_elapsed"] = new_data["timestamp"].dt.minute * 60 + new_data["timestamp"].dt.second
# Sélectionner les mêmes variables prédictives que pour l'entraînement
X_new = new_data[["Id_Website", "Id_proxy", "time_elapsed"]]

# Faire les prédictions sur les nouvelles données
predictions = model.predict(X_new)

# Afficher les prédictions
print(predictions)

[0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [38]:
new_data["Success"] = label_encoder.fit_transform(new_data["Success"])

target = new_data["Success"]


In [44]:
predictions - target.tolist()

array([ 0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0, -1,  1,  1,  0,  0,  0,
        0,  0, -1, -1,  0,  1, -1,  0,  1,  0,  0,  0, -1,  0, -1, -1,  0,
       -1,  0,  0,  0, -1,  0,  1,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,
       -1,  0,  0, -1,  0, -1,  1,  0,  1,  1, -1,  0,  0,  0, -1,  0,  0,
        1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,
        0,  0, -1,  0, -1,  0,  1,  1,  0,  0, -1,  0,  0,  0,  1, -1,  0,
       -1, -1,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,  1,  0,
        1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  1,
        0,  0,  0,  0, -1,  1,  1, -1,  1, -1,  0, -1, -1,  0,  0,  0,  0,
        0,  0, -1,  1,  1, -1,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
      dtype=int64)

In [43]:
accuracy = accuracy_score(target, predictions)
confusion_mat = confusion_matrix(target, predictions)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.6766169154228856
Matrice de confusion :
 [[134  21]
 [ 44   2]]


In [196]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = GradientBoostingClassifier()
pipeline_model6 = make_pmml_pipeline(model)
pipeline_model6.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model6.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.74375
Matrice de confusion :
 [[110   6]
 [ 35   9]]


In [197]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model6, "trained_model6.pmml")

In [194]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
# from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = SVC()
pipeline_model5 = make_pmml_pipeline(model)
pipeline_model5.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model5.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[116   0]
 [ 44   0]]


In [195]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model5, "trained_model5.pmml")

In [191]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = DecisionTreeClassifier()
pipeline_model4 = make_pmml_pipeline(model)
pipeline_model4.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model4.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.7125
Matrice de confusion :
 [[94 22]
 [24 20]]


In [192]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model4, "trained_model4.pmml")

In [137]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = KNeighborsClassifier()
pipeline_model3 = make_pmml_pipeline(model)
pipeline_model3.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model3.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[104  12]
 [ 32  12]]


In [138]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model3, "trained_model3.pmml")

In [133]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = MLPClassifier()
pipeline_model2 = make_pmml_pipeline(model)
pipeline_model2.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model2.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.74375
Matrice de confusion :
 [[115   1]
 [ 40   4]]


In [134]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model2, "trained_model2.pmml")

In [224]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = SGDClassifier()
pipeline_model7 = make_pmml_pipeline(model)
pipeline_model7.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = pipeline_model7.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[116   0]
 [ 44   0]]


In [225]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model7, "trained_model7.pmml")

In [278]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn2pmml import make_pmml_pipeline

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle SVM
model = LogisticRegression()
pipeline_model8 = make_pmml_pipeline(model)
pipeline_model8.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred_proba = pipeline_model8.predict_proba(X_test)
y_pred = np.argmax(y_pred_proba, axis=1)
# print(y_pred_proba)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)

Précision du modèle : 0.725
Matrice de confusion :
 [[116   0]
 [ 44   0]]


In [279]:
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline_model8, "trained_model8.pmml")

In [242]:
# Convert y_pred_proba to DataFrame
y_pred_proba_df = pd.DataFrame(y_pred_proba, columns=['Prob_0', 'Prob_1'])

# Reset index of X_test for proper concatenation
X_test_reset = X_test.reset_index(drop=True)

# Concatenate along the column axis
result = pd.concat([X_test_reset, y_pred_proba_df], axis=1)

print(result)


     Id_Website  Id_proxy  time_elapsed    Prob_0    Prob_1
0             7        21            81  0.745024  0.254976
1            38        38           206  0.716569  0.283431
2           684        42            47  0.772487  0.227513
3           231        12           124  0.723996  0.276004
4           190        50            79  0.767657  0.232343
..          ...       ...           ...       ...       ...
155         351        39            93  0.755498  0.244502
156         261        46           194  0.727650  0.272350
157         578        44           124  0.749816  0.250184
158         267        13            78  0.740302  0.259698
159          66        10            80  0.736903  0.263097

[160 rows x 5 columns]


In [244]:
result.to_csv("result.csv")