In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

# Charger le fichier CSV
data = pd.read_csv("pp.csv")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%H:%M:%S:%f")

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Enregistrer les données au format CSV
data.to_csv("pp_updated.csv", index=False)

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"])

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.hour * 3600 + data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


C:\Users\tjeff\AppData\Local\Temp\ipykernel_162828\1161532954.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data["timestamp"] = pd.to_datetime(data["timestamp"])


ParserError: second must be in 0..59: 0:10:95, at position 2

In [16]:
data = pd.read_csv("pp.csv", delimiter="\t")

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Id_Website  799 non-null    int64 
 1   Id_proxy    799 non-null    int64 
 2   Success     799 non-null    bool  
 3   timestamp   799 non-null    object
dtypes: bool(1), int64(2), object(1)
memory usage: 19.6+ KB


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.hour * 3600 + data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.7625
Matrice de confusion :
 [[108   8]
 [ 30  14]]


In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Charger le fichier CSV
data = pd.read_csv("pp.csv", delimiter="\t")

# Convertir la colonne timestamp en type datetime
data["timestamp"] = pd.to_datetime(data["timestamp"], format="%M:%S:%f")
data["tierces"] = data["timestamp"].dt.microsecond // 10000

# Encoder les variables catégorielles
label_encoder = LabelEncoder()
data["Success"] = label_encoder.fit_transform(data["Success"])

# Créer une nouvelle colonne "time_elapsed" en secondes
data["time_elapsed"] = data["timestamp"].dt.minute * 60 + data["timestamp"].dt.second + data["tierces"]

# Séparer les variables prédictives de la variable cible
X = data[["Id_Website", "Id_proxy", "time_elapsed"]]
y = data["Success"]

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialiser et entraîner le modèle
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Prédire sur l'ensemble de test
y_pred = model.predict(X_test)

# Évaluer les performances du modèle
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.7625
Matrice de confusion :
 [[106  10]
 [ 28  16]]


In [20]:
data["time_elapsed"]

0       57
1       26
2      105
3       76
4       50
      ... 
794     17
795    254
796     24
797    194
798    131
Name: time_elapsed, Length: 799, dtype: int32

In [35]:
new_data = pd.read_csv("new_data.csv", delimiter="\t")
new_data

Id_Website  Id_proxy  Success timestamp
0           388        24    False   0:32:13
1            72        11    False   0:01:40
2           424        31     True   0:21:18
3           714        35    False   0:38:13
4           395        35    False   0:04:37
..          ...       ...      ...       ...
196         724        58    False   0:02:93
197         452         2    False   0:22:18
198           5         5    False   0:50:08
199         160        23    False   3:10:75
200         448         5    False   3:08:51

[201 rows x 4 columns]

In [36]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Id_Website  201 non-null    int64 
 1   Id_proxy    201 non-null    int64 
 2   Success     201 non-null    bool  
 3   timestamp   201 non-null    object
dtypes: bool(1), int64(2), object(1)
memory usage: 5.0+ KB


In [37]:
#new_data = pd.read_csv("new_data.csv", delimiter="\t")

# Prétraiter les nouvelles données
# Assurez-vous d'appliquer les mêmes transformations que pour les données d'entraînement
new_data["timestamp"] = pd.to_datetime(new_data["timestamp"], format="%M:%S:%f")
new_data["tierces"] = new_data["timestamp"].dt.microsecond // 10000

new_data["time_elapsed"] = new_data["timestamp"].dt.minute * 60 + new_data["timestamp"].dt.second
# Sélectionner les mêmes variables prédictives que pour l'entraînement
X_new = new_data[["Id_Website", "Id_proxy", "time_elapsed"]]

# Faire les prédictions sur les nouvelles données
predictions = model.predict(X_new)

# Afficher les prédictions
print(predictions)

[0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [38]:
new_data["Success"] = label_encoder.fit_transform(new_data["Success"])

target = new_data["Success"]


In [44]:
predictions - target.tolist()

array([ 0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0, -1,  1,  1,  0,  0,  0,
        0,  0, -1, -1,  0,  1, -1,  0,  1,  0,  0,  0, -1,  0, -1, -1,  0,
       -1,  0,  0,  0, -1,  0,  1,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,
       -1,  0,  0, -1,  0, -1,  1,  0,  1,  1, -1,  0,  0,  0, -1,  0,  0,
        1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,
        0,  0, -1,  0, -1,  0,  1,  1,  0,  0, -1,  0,  0,  0,  1, -1,  0,
       -1, -1,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,  1,  0,
        1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  1,
        0,  0,  0,  0, -1,  1,  1, -1,  1, -1,  0, -1, -1,  0,  0,  0,  0,
        0,  0, -1,  1,  1, -1,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
      dtype=int64)

In [43]:
accuracy = accuracy_score(target, predictions)
confusion_mat = confusion_matrix(target, predictions)

print("Précision du modèle :", accuracy)
print("Matrice de confusion :\n", confusion_mat)


Précision du modèle : 0.6766169154228856
Matrice de confusion :
 [[134  21]
 [ 44   2]]
